---
- name: 'Check dir exists'
  file:
    path: '../{{ ansible_vault_dir }}'
    state: 'directory'
    mode: '0755'

# "is (not) exists" looks for a controller file, so not very useful
# confusingly, it looks in the pwd, not the playbook dir
- name: 'Create secret'
  when: 'ansible_vault_secret is not exists'
  copy:
    content: '{{ lookup("password", "/dev/null length=32") }}'
    dest: '../{{ ansible_vault_secret }}'
    mode: '0600'

- name: 'Delete old vault'
  file:
    path: '../{{ ansible_vault_file }}'
    state: 'absent'

# Put plaintext in /dev/shm so it's never in storage
- name: 'Create temporary path'
  register: 'ansible_vault_random_filename'
  tempfile:
    path: '/dev/shm'
    state: 'file'

- name: 'Create plaintext vault'
  template:
    src: 'vault.j2'
    dest: '{{ ansible_vault_random_filename.path }}'
    mode: '0600'

- name: 'Encrypt the lot'
  ansible_vault:
    mode: 'encrypt'
    password_file: '../{{ ansible_vault_secret }}'
    src: '{{ ansible_vault_random_filename.path }}'
    dest: '../{{ ansible_vault_file }}'

- name: 'Delete plaintext vault'
  file:
    path: '{{ ansible_vault_random_filename }}'
    state: 'absent'
...
# vim: set filetype=yaml
