---
ansible_vault_secret: '{{ ansible_vault_dir }}/{{ env }}-password.txt'
ansible_vault_file: '{{ ansible_vault_dir }}/{{ env }}-vault.yml'

repository_root: '/var/tmp/xbps-static'
repository_cwd: '{{ repository_root }}/var/cache/xbps'

repository_file: '/tmp/pid.{{ repository_port }}'
repository_port: '8000'

xbps_static_binary_path: '{{ repository_root }}/usr/bin'
xbps_static_repository: 'https://repo-default.voidlinux.org/current'

xbps_package_download:
  - 'acl-progs'
  - 'anope'
  - 'bash-completion'
  - 'bind-utils'
  - 'binutils'
  - 'borg'
  - 'botan'
  - 'chrony'
  - 'composer'
  - 'cronie'
  - 'curl'
  - 'dbus'
  - 'gcc'
  - 'git'
  - 'gitea'
  - 'glibc-devel'
  - 'gnupg2'
  - 'grafana'
  - 'inspircd'
  - 'jq'
  - 'keepalived'
  - 'kernel-libc-headers'
  - 'libdebuginfod'
  - 'libgcc-devel'
  - 'libgomp'
  - 'libldns'
  - 'libssp'
  - 'libssp-devel'
  - 'libstdc++-devel'
  - 'lighttpd'
  - 'logrotate'
  - 'lynis'
  - 'make'
  - 'mit-krb5'
  - 'mit-krb5-client'
  - 'mit-krb5-libs'
  - 'neofetch'
  - 'net-snmp'
  - 'nginx'
  - 'nodejs'
  - 'node_exporter'
  - 'nss'
  - 'nss-pam-ldapd'
  - 'openjdk17'
  - 'openldap'
  - 'openldap-tools'
  - 'openssh'
  - 'p11-kit'
  - 'pgweb'
  - 'php'
  - 'php-cgi'
  # - 'postgresql{{ postgresql_version }}'
  # - 'postgresql{{ postgresql_version }}-client'
  - 'prometheus'
  - 'python'
  - 'python3'
  - 'python3-aiohttp'
  - 'python3-defusedxml'
  - 'python3-dulwich'
  - 'python3-icalendar'
  - 'python3-Jinja2'
  - 'python3-MarkupSafe'
  - 'python3-mysqlclient'
  - 'python3-pip'
  - 'python3-pexpect'
  - 'python3-Twisted'
  - 'rsync'
  - 'rsyslog'
  - 'rsyslog-elasticsearch'
  - 'sssd'
  - 'strace'
  - 'tcpdump'
  - 'the_silver_searcher'
  - 'unbound'
  - 'unzip'
  - 'uwsgi'
  - 'vim'
  - 'xxd'
...
# vim: set filetype=yaml
