---
dependencies:
  - vars:
      packages:
        - 'chrony'
      packages_notifies:
        - 'Restart chronyd'
    role: 'meta_packages_install_xbps'
  - vars:
      templates:
        - path: '/etc/chrony.conf'
      templates_role: 'chrony_install'
      templates_notifies:
        - 'Restart chronyd'
    role: 'meta_templates'
  - vars:
      services:
        - 'chronyd'
      services_notifies:
        - 'Restart chronyd'
    role: 'meta_enable_services_runit'
  - vars:
      ka_name: 'time'
      ka_password: '{{ keepalived_auth_password }}'
    role: 'meta_keepalived'
  - vars:
      hosts_lookup: '{{ public_time_servers }}'
    role: 'meta_etc_hosts_add'
  - vars:
      rsyslog_names:
        - 'chronyd'
    role: 'meta_rsyslog_conf_add'
  - vars:
      iptables_rules:
        - ip: '{{ ansible_host }}'
          proto: 'udp'
          destination_address: '{{ netmask }}'
          destination_port: '123'
    role: 'meta_iptables_add'
  - vars:
      dns_group: 'auth'
      dns_extra:
        srv:
          - name: '_ntp._udp'
            port: '123'
    role: 'meta_dns_service_add'
...
# vim: set filetype=yaml
