---
- name: 'Check Ansible Vault loaded'
  hosts: 'all'
  become: no
  connection: 'local'
  run_once: yes
  gather_facts: no
  handlers:
    - import_tasks: '../handlers/main.yml'
  roles:
    - 'ansible_vault_check'
...
# vim: set filetype=yaml
