---
- name: 'Check Ansible version'
  hosts: 'all'
  become: no
  connection: 'local'
  run_once: yes
  gather_facts: no
  handlers:
    - import_tasks: '../handlers/main.yml'
  vars:
    ansible_version_min: '2.8.2'
    # pinned at 2.10.17 so we can still use cron module on /etc/crontab
    ansible_version_max: '2.10.17'
  roles:
    - 'ansible_version_check'
...
# vim: set filetype=yaml
