---
- name: 'Ansible checks'
  tags:
    - 'always'
  import_playbook: 'ansible_checks.yml'

- name: 'Sanitise cluster hosts'
  hosts: 'hosts_physical'
  become: yes
  gather_facts: no
  handlers:
    - import_tasks: '../handlers/main.yml'
  roles:
    - 'physicals_sanitise'
...
# vim: set filetype=yaml
