---
- import_playbook: 'check_ansible_version.yml'

- name: 'Boot tier 1'
  hosts: 'tier_1'
  gather_facts: no
  become: no
  handlers:
    - import_tasks: '../handlers/main.yml'
  roles:
    - 'tier_up'
...
# vim: set filetype=yaml
