---
# This could be done in the base image.
- name: 'Delete a lot of unneeded files'
  become: yes
  loop: '{{ base_rm_files }}'
  file:
    path: '{{ item }}'
    state: 'absent'

- name: 'Set random seed'
  notify: 'Restart sshd'
  become: yes
  community.general.filesize:
    path: '/var/lib/random-seed'
    size: '{{ "4 KB" | human_to_bytes }}'
    source: '/dev/urandom'

# TODO - split off base_install_common for shared tasks with physical_sanitise

- name: 'Create UTF-8 locale'
  localedef:
    charmap: 'UTF-8'
    locale: 'en_GB'  # aka input
    path: '/usr/lib64/locale/en_GB.UTF-8'  # aka outputpath
...
# vim: set filetype=yaml
