---
- name: 'List shutdown guests'
  register: 'pre_boot_status'
  delegate_to: '{{ hypervisor_host }}'
  virt:
    command: 'list_vms'
    state: 'shutdown'
    uri: 'qemu:///session'

- name: 'Boot shutdown guests'
  when: 'fqdn in pre_boot_status.list_vms'
  delegate_to: '{{ hypervisor_host }}'
  virt:
    name: '{{ fqdn }}'
    state: 'running'
    uri: 'qemu:///session'

- name: 'Wait for hosts to be up'
  when: 'fqdn in pre_boot_status.list_vms'
  wait_for_connection:
    delay: 5
    sleep: 5
    timeout: 3600 # can take a while when all are booting

- name: 'Pause for hosts to settle'
  when: 'fqdn in pre_boot_status.list_vms'
  delegate_to: '{{ hypervisor_host }}'
  loop_control:
    label: 'Pausing'
  pause:
    seconds: '{{ boot_post_delay }}'
...
# vim: set filetype=yaml
