---
- name: 'Install keepalived'
  become: yes
  xbps:
    name: 'keepalived'

- name: 'Configure keepalived'
  become: yes
  loop:
    - '/etc/keepalived/keepalived.conf'
  template:
    src: '{{ item[1:] }}'
    dest: '{{ item }}'
    mode: '0644'
    owner: 'root'
    group: 'root'

- name: 'Create service symlink'
  become: yes
  file:
    src: '/etc/sv/keepalived'
    dest: '/var/service/keepalived'
    state: 'link'
    mode: '0777'
    owner: 'root'
    group: 'root'

- name: 'Restart keepalived service'
  become: yes
  service:
    name: 'keepalived'
    state: 'restarted'
...
# vim: set filetype=yaml
