---
- name: 'Wait for chronyd to synchronise with an upstream server'
  register: 'rg_wait_sync'
  vars:
    s_match: '^Stratum'
    s_value: '0'
    lines: '{{ rg_wait_sync.stdout_lines }}'
    line: "{{ lines | select('match', s_match) | first }}"
  retries: 60
  delay: 1
  until:
    - "(line.split(' ') | last) != s_value"
  chrony:
    mode: 'tracking'

#- name: 'Debug'
#  vars:
#    s_match: '^Stratum'
#    s_value: '0'
#    lines: '{{ rg_wait_sync.stdout_lines }}'
#    line: "{{ lines | select('match', s_match) | first }}"
#  debug:
#    msg: "{{ line.split(' ') | last }}"

- name: 'Step system clock'
  chrony:
    mode: 'make_step'

- name: 'Sync hardware clock'
  hwclock:
    mode: 'systohc'
...
# vim: set filetype=yaml
