---
host_templates:
  - path: '/etc/qemu/bridge.conf'
    mode: '0644'
  - path: '/etc/machine-id'
    mode: '0444'
  - path: '/etc/hostname'
  - path: '/etc/sudoers'
    mode: '0440'
  - path: '/etc/sudoers.d/wizards'
    mode: '0440'
  - path: '/etc/sudoers.d/ansible'
    mode: '0440'
  - path: '/etc/dhcpcd.conf'
  - path: '/etc/dhcpcd.exit-hook'
  - path: '/etc/default/locale'
  - path: '/etc/default/grub'
  - path: '/etc/locale.conf'
  - path: '/etc/ssh/sshd_config'

host_rm_files:
  - '/etc/ssh/ssh_host_dsa_key'
  - '/etc/ssh/ssh_host_dsa_key.pub'
  - '/etc/ssh/ssh_host_ed25519_key'
  - '/etc/ssh/ssh_host_ed25519_key.pub'
  - '/etc/ssh/ssh_host_ecdsa_key'
  - '/etc/ssh/ssh_host_ecdsa_key.pub'
  - '/etc/ssh/ssh_host_rsa_key'
  - '/etc/ssh/ssh_host_rsa_key.pub'
  - '/var/service/agetty-hvc0'
  - '/var/service/agetty-hvsi0'
  - '/var/service/agetty-tty4'
  - '/var/service/agetty-tty5'
  - '/var/service/agetty-tty6'

host_packages:
  - 'tmux'
  - 'libguestfs'
  - 'netcat'

host_gateway: '10.7.6.254'

host_dns_servers:
  - '8.8.8.8'

iptables_check_pidfile: '/tmp/iptables-sync.pid'
iptables_check_timeout: 60

iptables_ruleset: '/etc/iptables/iptables.rules'
iptables_known_good: '/tmp/iptables.known-good'
iptables_new: '/tmp/iptables.rules'

grub_default: 'saved'
grub_savedefault: 'true'
grub_timeout: '3'
grub_distributor: 'Void'
grub_disable_os_prober: 'true'
grub_gfxpayload_linux: 'text'
grub_gfxmode: '1920x1080x32'
grub_theme: '/boot/grub/themes/grub2-solarized-light/theme.txt'
grub_background: '/usr/share/void-artwork/splash.png'
grub_cmdline_linux_default:
  - 'loglevel=4'
  - 'udev.log_level=4'
  - 'slub_debug=P'
  - 'page_poison=1'
  - 'quiet'
  - 'nofb'
  - 'nomodeset'
  - 'net.ifnames=0'
  - 'drm.debug=0x1e'
  - 'apparmor=1'
  - 'security=apparmor'
  - 'keymap=uk'
  - 'intel_idle.max_cstate=1'
  - 'cryptomgr.notests'
  - 'initcall_debug'
  - 'intel_iommu=igfx_off'
  - 'no_timer_check'
  - 'noreplace-smp'
  - 'page_alloc.shuffle=1'
  - 'rcupdate.rcu_expedited=1'
  - 'tsc=reliable'
  - 'console=tty2'
  - 'vt.default_red=0xee,0xdc,0x85,0xb5,0x26,0xd3,0x2a,0x07,0xfd,0xcb,0x93,0x83,0x65,0x6c,0x58,0x00'
  - 'vt.default_grn=0xe8,0x32,0x99,0x89,0x8b,0x36,0xa1,0x36,0xf6,0x4b,0xa1,0x94,0x7b,0x71,0x6e,0x2b'
  - 'vt.default_blu=0xd5,0x2f,0x00,0x00,0xd2,0x82,0x98,0x42,0xe3,0x16,0xa1,0x96,0x83,0xc4,0x75,0x36'
...
# vim: set filetype=yaml
