---
- name: 'Update repository URL'
  become: yes
  vars:
    file: '/etc/xbps.d/00-repository-main.conf'
  template:
    src: '{{ file[1:] }}.j2'
    dest: '{{ file }}'

# TODO: does this belong here?
- name: 'Add public resolver'
  register: 'rg_add_resolver'
  become: yes
  lineinfile:
    path: '/etc/resolv.conf'
    line: 'nameserver 8.8.8.8'
    insertafter: 'search {{ domain }}'
    backup: yes  # to restore the file afterwards

- name: 'Install packages'
  register: 'rg_install'
  become: yes
  vars:
    e_already: 'already installed'
  notify: '{{ packages_notifies }}'
  changed_when:
    - 'rg_install.rc == 0'
    - 'e_already not in rg_install.stdout'
  failed_when:
    - 'rg_install.rc > 0'
    - 'e_already not in rg_install.stdout'
  xbps_uncommon:
    packages: '{{ packages }}'

- name: 'Restore backup resolv.conf file'
  when: 'rg_add_resolver.changed'
  become: yes
  move:
    src: '{{ rg_add_resolver.backup }}'
    dest: '/etc/resolv.conf'
    insist: yes
...
# vim: set filetype=yaml
