---
- name: 'Copy base image'
  copy:
    src: '../annex/{{ virts_base_image }}'
    dest: '{{ virts_image_dest }}/base.qcow2'
    local_follow: yes # locally, follow annex symlinks
    owner: '{{ virts_user }}'
    group: '{{ virts_user }}'
    mode: '0664' # needs to have g+w to work

- name: 'Update libguestfs appliance'
  libguestfs:
    mode: 'update_appliance'
...
# vim: set filetype=yaml
