---
- name: 'List running guests'
  register: 'pre_shutdown_status'
  delegate_to: '{{ hypervisor_host }}'
  virt:
    command: 'list_vms'
    state: 'running'
    uri: 'qemu:///session'

- name: 'Shutdown running guests'
  when: 'fqdn in pre_shutdown_status.list_vms'
  delegate_to: '{{ hypervisor_host }}'
  virt:
    name: '{{ fqdn }}'
    state: 'shutdown'
    uri: 'qemu:///session'

- name: 'Undefine virts'
  delegate_to: '{{ hypervisor_host }}'
  virt:
    name: '{{ fqdn }}'
    command: 'undefine'
    uri: 'qemu:///session'
    # force: yes

# Don't delete disks. Might be wanted for analysis.
...
# vim: set filetype=yaml
